---
#-------------------------------
# Site Settings
title: anphx
description: Personal website of An Pham. I'm a software engineer, photographer, and coffee enthusiast. I blog about tech, photography, and life. # Add a description of your site
# logo: "/images/logo.svg" # You can add own logo. For example "/images/logo.svg".
# logo_dark: "/images/logo-dark.svg"
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.
tags: [tech, photography, lifestyle] # Add tags for your site

#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: "Latest"
      url: "/latest/"
    - title: "Captures"
      url: "/captures/"
    - title: "Resources"
      submenu:
        - url: "/about/"
          title: "About"
        - url: "/contact/"
          title: "Contact"

# Call to action button
cta_button:
  enable: true
  cta_button_link: "/contact/"
  cta_button_text: Get in touch

#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_title: Crafting Digital Realities.
  hero_description: Turning caffeine, code, and creativity into digital magic. Whether it's debugging lines or capturing light, it's all about creating art.

#-------------------------------
# Tags Section Settings
tags_section:
  enable: true
  number_posts: 3 # To control how many posts to show under each tag section, set the value to a number. Three is the default.
  number_columns: 3 # You can specify the number of columns from 1-4 for large screen resolution. By default, the theme uses three columns grid.
  # tags:
  #   - tag: "lifestyle"
  #   - tag: "sport"
  # - tag: "techno"

# You can add many tag sections to the homepage; each section will show the recent posts by the tag.

#-------------------------------
# Authors Section Settings
authors_section:
  enable: true
  section_title: Meet our authors

#-------------------------------
# Footer Settings
footer_description: Welcome to my blog - a mix of code, cameras, and caffeinated musings. From debugging life's glitches to capturing its best angles, you'll find a little bit of everything here—served with a side of wit and the occasional lens flare!

# Social Links
social:
  - { icon: "github", link: "https://github.com/anphx" }
  - { icon: "linkedin", link: "https://www.linkedin.com/in/an-pham/" }
  - { icon: "instagram", link: "https://www.instagram.com/anpham.aph/" }

# Example of adding a new link to the footer - {icon: "instagram", link: "https://instagram.com"}
# Other icons can be found at https://ionicons.com/v4/

#-------------------------------
# Newsletter Settings
mailchimp_settings:
  enable: false
  mailchimp_title: Get interesting news
  mailchimp_description: Subscribe to our newsletter and we’ll send you the emails of latest posts.
  mailchimp_identifier: frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
  mailchimp_input_text: Your email address
  mailchimp_button_text: Subscribe

#-------------------------------
# Contact Settings
contact:
  email: xovvblez # Add your form_id
  description: Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon as possible.
# NOTE
# Danto theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.

#-------------------------------
# Comment Section (Disqus)
# disqus_identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test

#-------------------------------
# Google Analytics
# google_analytics: # Add your GA Tracking Id
